# Generated by Django 6.0.4 on 2026-05-09 09:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('nin', models.CharField(max_length=20, unique=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_credit_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('steel', 'Steel / Iron Bars'), ('nails', 'Nails'), ('hardware', 'Hardware'), ('roofing', 'Roofing')], max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_stock_level', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('bags', 'Bags')], default='pcs', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit (Pay Later)'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20)),
                ('credit_due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('critical', 'Critical - Below 10 units'), ('low', 'Low Stock - Below 30 units'), ('normal', 'Normal Stock'), ('overstock', 'Overstock')], default='normal', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit')], default='cash', max_length=20)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sold_by', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sale')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('due_date', models.DateField()),
                ('is_cleared', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.stock')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.supplier')),
            ],
        ),
    ]
