# Generated by Django 6.0.4 on 2026-05-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_deposit_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
