# Generated by Django 6.0.4 on 2026-05-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_customer_name_deposit_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='customer',
            new_name='customer_name',
        ),
    ]
