# Generated by Django 6.0.4 on 2026-05-18 08:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_customer_deposit_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='sale',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
