# Generated by Django 6.0.4 on 2026-05-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_customer_distance_km_sale_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.sale'),
            preserve_default=False,
        ),
    ]
