# Generated by Django 6.0.4 on 2026-05-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_deposit_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
